### ISSUE TITLE
brainwallet

### ISSUE THREAD

**Issue by curiosity81** [IamRaviTejaG/NodeJS#5]
Hi Ravi, 

I want to ask you if you could delete the fork

IamRaviTejaG/brainwallet

and, if necessary, fork instead the renamed project

https://github.com/curiosity81/stringwallet

Best regards,
cu

P.S.: there seemed no other way to contact you

**Comment by IamRaviTejaG-zz** [comment]
@curiosity81 Hey there! Deleted the fork. And no problem with contacting me here. 👍

**Comment by curiosity81** [comment]
Thanks. :-)
